### PR TITLE
ISSUE-39: require grape/rabl

### PR DESCRIPTION
**Pull request by martinezcoder**
If I include this requirement, this error is fixed: [ISSUE-39](https://github.com/LTe/grape-rabl/issues/39)

### CODE REVIEW

**Comment by dblock** [comment]
I think this is a good idea, we actually say in README to `require 'grape/rabl`, would you please take that out since this fixes that?

**Comment by martinezcoder** [comment]
done! please review, I think it was just to remove all the `require grape/rabl` from the README

**Comment by dblock** [comment]
Merged via https://github.com/LTe/grape-rabl/commit/94de02b398561b77e9e3db4fb554080bf80d05ff (had to fix a typo in CHANGELOG and stuff).

**Comment by martinezcoder** [comment]
:+1:

**Pull request closed without merging**
